name: Go Build and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        output_name="xfer-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          output_name="${output_name}.exe"
        fi
        go build -v -o $output_name ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.goos }}-${{ matrix.goarch }}-binary
        path: xfer-${{ matrix.goos }}-${{ matrix.goarch }}*
