name: Go Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        output="xfer-${GOOS}-${GOARCH}"
        [ "$GOOS" = "windows" ] && output="${output}.exe"
        CGO_ENABLED=0 go build -v -o $output ./src/main.go

    #- name: Upload Release Asset
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    files: xfer-${{ matrix.goos }}-${{ matrix.goarch }}*
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
